### ISSUE TITLE
using screen vs.TVHEADLESS 

### ISSUE THREAD

**Issue by gitttt** [zardus/idalink#11]
Any reason why you use screen and not set the TVHEADLESS env variable to 1?

**Comment by zardus** [comment]
I'd never heard of a TVHEADLESS option! `screen` was the first thing I reached for. Do you have it working with TVHEADLESS=1?

**Comment by gitttt** [comment]
Hey!
My first experiments show that TVHEADLESS=1 works. 
I am running IDA 6.9 on Linux (idaq64) on Ubuntu 14.04.

I was just wondering if you had any special reason to prefer screen over TVHEADLESS.
Do you just used screen to have a console version without gui? Or do you use any other (more sophisticated?) screen features?

**Comment by zardus** [comment]
TBH, I don't remember. My guess is that it was a temporary measure instead of reading IDA's docs :-)

A PR getting rid of the screen requirement would be awesome!
