### ISSUE TITLE
OS X/macOS and/or virtual environments

### ISSUE THREAD

**Issue by TheRealTroff** [zardus/idalink#15]
Is this known to work on OS X/macOS? If so, is it known to work if installed in a virtualenv?

The reason I ask is of course that I don't seem to get a connection and I know from experience that getting a launched process to run the right python can be tricky on OS X.

**Comment by zardus** [comment]
To my knowledge, idalink *only* works in a virtualenv; I've never tried it outside of one.

Regarding OSX, none of us have access to an OSX version of IDA. For sure, you'll need to link "idal" to point to whatever the OSX binary is named, and you'll need `screen`, as things work now. `idalink` will launch `screen` with `idal` inside it, and IDA should automatically use its bundled Python (assuming this is a thing on OSX IDA).

**Comment by TheRealTroff** [comment]
Yeah, actually none of those assumptions hold. Let me know if you're interested in the details. Otherwise I'll be back with a PR.
