### ISSUE TITLE
0.11 on pypi vs 0.10 here?

### ISSUE THREAD

**Issue by TheRealTroff** [zardus/idalink#17]
What I'm "really" trying to do is use `angr` with the ida loader, so my original `idalink` install was done with `pip install angr`. This repo appears to be clearly a further development, but at the same time `cle` used by `angr` seems to rely on argument names that are different in the two sources. Is the intention for `cle` to work with the latest `idalink` should the used by `cle/angr/pypi` be considered a fork?

**Comment by zardus** [comment]
Ideally, `idalink` (this repo) should work with `CLE` as a loader backend, but we don't have any automated tests because IDA is IDA. As we *very* rarely use the IDA backend, it's possible that the projects diverged and CLE's interaction with idalink needs to be updated...

**Comment by Manouchehri** [comment]
I believe 0.11 on PyPI is from commit 7cea20535a6c5c8d5406ba3286a62653eaf4ea98 here. 

Version numbers are a bit confusing; can I bump this repo to 0.12 to make it a bit more clear?

**Comment by zardus** [comment]
Sure!
