### ISSUE TITLE
GPLv3 vs. BSD license contradictions

### ISSUE THREAD

**Issue by afaerber** [zardus/idalink#19]
Despite the LICENSE file having been changed to BSD-2-Clause as part of issue #7, all `idalink/*.py` files still have headers indicating they're under GPL-3.0+ license.

Can you please clarify whether those files are intended to be under BSD now and, if so, fix all the files to say so?
Otherwise the GPLv3 license text will be needed, too.

**Comment by zardus** [comment]
Things are intended to be under BSD, as per the discussion in #14. Thanks for pointing this out! I updated the files.
